spring:
  application:
    name: eurekaserver
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
logging:
  level:
    com:
      netflix:
        eureka: off
        discovery: off
server:
  port: 8761